export const ProductDate = [
  {
    title: "T shirt red",
    price: 49,
    quantity: 1,
    id: 1,
    availableSizes: ["L", "M", "X"],
  },
  {
    title: "T shirt green",
    price: 79,
    quantity: 1,
    id: 2,
    availableSizes: ["S", "M", "X"],
  },
  {
    title: "T shirt gray",
    price: 45,
    quantity: 1,
    id: 3,
    availableSizes: ["XL", "M", "XXL"],
  },
  {
    title: "T shirt black",
    price: 39,
    quantity: 1,
    id: 4,
    availableSizes: ["S", "M", "L"],
  },
  {
    title: "T shirt white",
    price: 99,
    quantity: 1,
    id: 5,
    availableSizes: ["XL", "XXL"],
  },
  {
    title: "T shirt orange",
    price: 66,
    quantity: 1,
    id: 6,
    availableSizes: ["XS", "X"],
  },
  {
    title: "T shirt pink",
    price: 29,
    quantity: 1,
    id: 7,
    availableSizes: ["S", "L"],
  },
  {
    title: "T shirt blue",
    price: 80,
    quantity: 1,
    id: 8,
    availableSizes: ["XXL", "XS"],
  },
  {
    title: "T shirt yellow",
    price: 55,
    quantity: 1,
    id: 9,
    availableSizes: ["L", "X"],
  },
  {
    title: "T shirt brown",
    price: 19,
    quantity: 1,
    id: 10,
    availableSizes: ["XL", "X"],
  },
];
